import type { Metadata } from "next";
import "@/styles/main.scss";
import Providers from "@/providers";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Next13 Data Fetching Design Patterns",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box py={20} as="main">
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
